"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Shield, ArrowLeft, AlertTriangle } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-mesh-light dark:bg-mesh-dark transition-colors duration-500">
            <nav className="border-b border-purple-200/30 dark:border-purple-500/20 backdrop-blur-xl bg-white/80 dark:bg-purple-950/30">
                <div className="container mx-auto px-4 py-4 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2">
                        <Shield className="h-8 w-8 text-primary" />
                        <span className="text-xl font-bold text-gradient-royal">
                            ContractLens AI
                        </span>
                    </Link>
                    <div className="flex items-center gap-3">
                        <ThemeToggle />
                        <Link href="/">
                            <Button variant="ghost" size="sm">
                                <ArrowLeft className="mr-2 h-4 w-4" />
                                Back to Home
                            </Button>
                        </Link>
                    </div>
                </div>
            </nav>

            <div className="container mx-auto px-4 py-12 max-w-4xl">
                <Card className="glass-light dark:glass-royal">
                    <CardHeader>
                        <CardTitle className="text-3xl text-gradient-royal">Terms of Service</CardTitle>
                    </CardHeader>
                    <CardContent className="prose prose-invert max-w-none space-y-6">
                        <p className="text-muted-foreground">
                            Last updated: January 16, 2026
                        </p>

                        <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4 flex gap-3">
                            <AlertTriangle className="h-5 w-5 text-yellow-500 flex-shrink-0 mt-0.5" />
                            <div>
                                <h3 className="text-lg font-semibold text-yellow-500 mb-2">
                                    Important Disclaimer
                                </h3>
                                <p className="text-muted-foreground text-sm">
                                    ContractLens AI is <strong>NOT a substitute for legal
                                        advice</strong>. This tool provides automated analysis for
                                    informational purposes only. Always consult with a qualified
                                    attorney before making legal decisions.
                                </p>
                            </div>
                        </div>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">For Informational Purposes Only</h2>
                            <p className="text-muted-foreground">
                                ContractLens AI analyzes contract text using AI and provides
                                risk scores, clause classifications, and suggestions. This
                                output is:
                            </p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-3">
                                <li>Generated by AI and may contain errors or inaccuracies</li>
                                <li>Not tailored to your specific legal jurisdiction</li>
                                <li>Not a replacement for professional legal review</li>
                                <li>Provided "as-is" without warranties of any kind</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">No Legal Advice</h2>
                            <p className="text-muted-foreground">
                                The use of ContractLens AI does not create an attorney-client
                                relationship. We do not provide legal advice, legal opinions,
                                or recommendations specific to your situation.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">Acceptable Use</h2>
                            <p className="text-muted-foreground mb-3">You agree to:</p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                <li>
                                    Upload only contracts you have the right to analyze
                                </li>
                                <li>
                                    Not use the service for illegal purposes or to violate any
                                    laws
                                </li>
                                <li>
                                    Respect rate limits and not attempt to abuse or overload the
                                    service
                                </li>
                                <li>
                                    Not try to reverse engineer, extract, or steal the AI models
                                </li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">Limitation of Liability</h2>
                            <p className="text-muted-foreground">
                                ContractLens AI and its creators are not liable for:
                            </p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-3">
                                <li>
                                    Any decisions you make based on the analysis provided
                                </li>
                                <li>
                                    Errors, omissions, or inaccuracies in the AI-generated output
                                </li>
                                <li>
                                    Any damages resulting from your use or inability to use the
                                    service
                                </li>
                                <li>
                                    Loss of data, contracts, or business opportunities
                                </li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">No Guarantees</h2>
                            <p className="text-muted-foreground">
                                We do not guarantee that:
                            </p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-3">
                                <li>
                                    The service will identify all risks in your contract
                                </li>
                                <li>
                                    The risk scores or severity levels are accurate
                                </li>
                                <li>
                                    The suggested edits will resolve all legal issues
                                </li>
                                <li>
                                    The service will be available at all times without
                                    interruption
                                </li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">Your Responsibility</h2>
                            <p className="text-muted-foreground">
                                You are solely responsible for:
                            </p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-3">
                                <li>
                                    Verifying any information provided by ContractLens AI
                                </li>
                                <li>
                                    Consulting with qualified legal professionals
                                </li>
                                <li>
                                    Understanding the contracts you sign
                                </li>
                                <li>
                                    Complying with all applicable laws and regulations
                                </li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">Changes to Terms</h2>
                            <p className="text-muted-foreground">
                                We may update these terms at any time. Continued use of the
                                service after changes constitutes acceptance of the new terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-semibold mb-3">Contact</h2>
                            <p className="text-muted-foreground">
                                If you have questions about these terms, please contact{" "}
                                <span className="text-gradient-royal font-semibold">Faizal Hussain</span>{" "}
                                via our GitHub repository.
                            </p>
                        </section>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
